# Generated by Django 3.2.6 on 2021-08-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20210816_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='winpercent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
